[env:LilyGo_T_Connect_Pro]
extends = esp32
board = esp32s3_flash_16MB

monitor_speed = 115200 ;Serial Baud Rate Setting

; debug_tool = esp-builtin
; upload_protocol = esp-builtin
upload_speed = 921600 ; 460800, 512000, 460800, 256000, 115200
board_upload.flash_size = 16MB 

board_build.arduino.memory_type = qio_opi ;Enable internal PSRAM
; board_build.memory_type = qio_qspi ;Enable external PSRAM

board_build.arduino.partitions = partitions-16MB-safeboot.csv 

upload_command = pio pkg exec -p "tool-esptoolpy" -- esptool -b 921600 write_flash 0x0000 ${platformio.build_dir}/${this.__env__}/bootloader.bin 0xE000 otadata.bin 0x8000 ${platformio.build_dir}/${this.__env__}/partitions.bin 0x10000 safeboot-s3.bin 0xC0000 ${platformio.build_dir}/${this.__env__}/firmware.bin

lib_ignore =
	AceButton
	Adafruit TCA8418
	epdiy
	es7210
	ESP32-audioI2S
	GxEPD2
	lvgl
	SensorLibTDECKpro
	TFT_eSPI
	TinyGSM

lib_deps = 
	${libs.lib_deps}
	${esp32libs.lib_deps}
	ropg/Heltec_ESP32_LoRa_v3

	; Display Library
	moononournation/GFX Library for Arduino @ 1.6.0

	; Ethernet
    https://github.com/meshtastic/ETHClass2/archive/v1.0.0.zip
	arduino-libraries/Ethernet@^2.0.2

build_flags = 
	${esp32.build_flags}
	${common.build_flags}
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D MONITOR_SPEED=${upload_settings.monitor_speed}
	-D BOARD_T_CONNECT_PRO="esp32s3_flash_16MB"
	-I variants/${this.__env__}

	-D USER_SETUP_LOADED
	-D TFT_WIDTH=222
	-D TFT_HEIGHT=480
	-D TFT_ROTATION=3
	-D ST7735_DRIVER
	-D ST7735_GREENTAB160x80

;Wiring an ST7789 (SPI):
;VCC: 3.3V
;GND: Ground
;SCL/SCK: SPI Clock Pin
;SDA/MOSI: SPI MOSI Pin
;RES/RST: Digital IO (Reset)
;DC: Digital IO (Data/Command)
;CS: Digital IO (Optional, if not present, the display is always active) 
	-D TFT_RGB_ORDER=TFT_BGR
	-D TFT_MOSI=11
	-D TFT_MISO=13
	-D TFT_SCLK=12
	-D TFT_CS=21
	-D TFT_DC=41
	-D TFT_RST=42
	-D TFT_BL=46
	-D TFT_BACKLIGHT_ON=1
	-D TOUCH_CS=-1
	-D LOAD_GLCD
	-D LOAD_FONT2
	-D LOAD_FONT4
	-D LOAD_FONT6
	-D LOAD_FONT7
	-D LOAD_FONT8
	-D SPI_FREQUENCY=40000000
	-D USE_HSPI_PORT
