[env:T-ETH-ELITE_1262]
extends = esp32
board = esp32-s3-devkitc-1-n16r8
board_build.partitions = partitions-4MB-safeboot.csv

upload_protocol = custom
upload_command = python3 ~/.platformio/packages/tool-esptoolpy/esptool.py -b 921600 write_flash 0x0000 ${platformio.build_dir}/${this.__env__}/bootloader.bin 0xE000 otadata.bin 0x8000 ${platformio.build_dir}/${this.__env__}/partitions.bin 0x10000 safeboot-s3.bin 0xC0000 ${platformio.build_dir}/${this.__env__}/firmware.bin

monitor_speed = 115200
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
monitor_filters = esp32_exception_decoder

lib_ignore = Adafruit TCA8418, epdiy, es7210, ESP32-audioI2S, GxEPD2, lvgl, TFT_eSPI, TinyGSM

lib_extra_dirs = lib

lib_deps =
    ${libs.lib_deps}
    ${esp32libs.lib_deps}
    adafruit/Adafruit NeoPixel@^1.12.5
    https://github.com/meshtastic/ETHClass2/archive/v1.0.0.zip
	arduino-libraries/Ethernet@^2.0.2

build_flags =
    ${esp32.build_flags}
    ${common.build_flags}
	-DARDUINO_USB_MODE=1
    -D MONITOR_SPEED=${upload_settings.monitor_speed}
    -D BOARD_T_ETH_ELITE="esp32-s3-devkitc-1-n16r8"
    -D BOARD_E22
    -I variants/${this.__env__}
    -DCORE_DEBUG_LEVEL=0
    -Wno-unused-parameter