[env:E22_1262_S3-DevKitC-1-N16R8]
extends = esp32_s3
board = esp32-s3-devkitc-1-n16r8
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
monitor_filters = esp32_exception_decoder
monitor_dtr = 0
monitor_rts = 0

lib_ignore =
	AceButton
	Adafruit TCA8418
	epdiy
	ESP32-audioI2S
	lvgl
	SensorLibTDECKpro
	TFT_eSPI
	TinyGSM
	XPowersLib

lib_deps = 
	${libs.lib_deps}
	${esp32libs.lib_deps}
	adafruit/Adafruit NeoPixel@^1.12.5

	; Display Library
	olikraus/U8g2@^2.36.5
	
build_flags = 
	${esp32.build_flags}
	${common.build_flags}
	
    -DARDUINO_USB_CDC_ON_BOOT=0

	-D MONITOR_SPEED=${upload_settings.monitor_speed}
	-D BOARD_E22_S3="esp32-s3-devkitc-1-n16r8"
	-I variants/${this.__env__}