[nrf52]
platform = nordicnrf52
board = rak4630
framework = arduino
extends = upload_settings

lib_ignore = Adafruit TCA8418, epdiy, es7210, ESP32-audioI2S, GxEPD2, lvgl, SensorLib, TinyGSM, U8g2

[env:heltec_t114]
extends = nrf52
lib_deps = 
	${libs.lib_deps}
	${nrf52libs.lib_deps}
	https://github.com/adafruit/Adafruit-ST7735-Library

lib_archive = no
build_flags = 
	${nrf52.build_flags}
	${common.build_flags}

	-D BOARD_HELTEC_T114="T114"

	-D USER_SETUP_LOADED
	-D TFT_WIDTH=135
	-D TFT_HEIGHT=240
	-D TFT_ROTATION=3
	-D ST7735_DRIVER
	-D ST7735_GREENTAB160x80

;Wiring an ST7789 (SPI):
;VCC: 3.3V
;GND: Ground
;SCL/SCK: SPI Clock Pin
;SDA/MOSI: SPI MOSI Pin
;RES/RST: Digital IO (Reset)
;DC: Digital IO (Data/Command)
;CS: Digital IO (Optional, if not present, the display is always active) 

	-D TFT_RGB_ORDER=TFT_BGR
	-D TFT_MOSI=41
	-D TFT_MISO=43
	-D TFT_SCLK=40
	-D TFT_CS=11
	-D TFT_DC=12
	-D TFT_RST=2
	-D TFT_BL=21
	-D TFT_BACKLIGHT_ON=1
	-D TOUCH_CS=-1
	-D LOAD_GLCD
	-D LOAD_FONT2
	-D LOAD_FONT4
	-D LOAD_FONT6
	-D LOAD_FONT7
	-D LOAD_FONT8
	-D SPI_FREQUENCY=40000000
	-D USE_HSPI_PORT

	-D MONITOR_SPEED=${upload_settings.monitor_speed}
	-D SERIAL_BUFFER_SIZE=256
	-Isrc/nrf52
	-I variants/${this.__env__}