[env:heltec_wifi_lora_32_V2]
extends = esp32_classic
board = heltec_wifi_lora_32_V2

lib_ignore =
	AceButton
	Adafruit TCA8418
	epdiy
	ESP32-audioI2S
	lvgl
	SensorLibTDECKpro
	TFT_eSPI
	TinyGSM
	XPowersLib

lib_deps = 
	${libs.lib_deps}
	${esp32libs.lib_deps}
	
	; Display Library
	olikraus/U8g2@^2.36.5

build_flags = 
	${esp32.build_flags}
	${common.build_flags}
	-D BOARD_HELTEC="heltec"
	-I variants/${this.__env__}