[env:ttgo-lora32-v21]
extends = esp32_classic
board = ttgo-lora32-v21

lib_ignore =
	AceButton
	Adafruit TCA8418
	epdiy
	ESP32-audioI2S
	GxEPD2
	lvgl
	SensorLibTDECKpro
	TFT_eSPI
	TinyGSM
	XPowerLib

lib_deps = 
	${libs.lib_deps}
	${esp32libs.lib_deps}

	; Display Library
	olikraus/U8g2@^2.36.5
	
build_flags = 
	${esp32.build_flags}
	${common.build_flags}
	-D BOARD_TLORA_OLV216="ttgo-lora32-v21"
	-I variants/${this.__env__}