[nrf52]
platform = nordicnrf52
board = rak4630
framework = arduino
extends = upload_settings
src_filter = 
	+<*>
	-<esp32/*>
	-<Displays/*>
	-<Fonts/*>
	-<GFX_Root/*>
	-<Platforms/*>
	-<safeboot/*>
	-<t-deck/*>
	-<t-deck-pro/*>
	-<t5-epaper/*>
	-<tinyxml_function.cpp>
	+<../variants/wiscore_rak4631/*>
lib_ignore = Adafruit TCA8418, epdiy, es7210, ESP32-audioI2S, GxEPD2, lvgl, SensorLib, AceButton, TFT_eSPI, TinyGSM
build_flags = 
	${common.build_flags}
	-D BOARD_RAK4630="RAK4630"
	-D MONITOR_SPEED=${upload_settings.monitor_speed}
	-D SERIAL_BUFFER_SIZE=256
	-Isrc/nrf52

[env:wiscore_rak4631]
extends = nrf52
lib_deps = 
	${libs.lib_deps}
	${nrf52libs.lib_deps}
	olikraus/U8g2@^2.36.5
lib_archive = no
build_flags = 
	${nrf52.build_flags}
	-I variants/${this.__env__}