[nrf52]
platform = nordicnrf52
board = rak4630
framework = arduino
extends = upload_settings
build_src_filter = 
	+<*>
	-<esp32/*>
	-<Displays/*>
	-<Fonts/*>
	-<GFX_Root/*>
	-<Platforms/*>
	-<safeboot/*>
	-<t-deck/*>
	-<t-deck-pro/*>
	-<t5-epaper/*>
	-<tinyxml_function.cpp>
	+<../variants/wiscore_rak4631/*>
build_flags = 
	${common.build_flags}
	-D BOARD_RAK4630="RAK4630"
	-D MONITOR_SPEED=${upload_settings.monitor_speed}
	-D SERIAL_BUFFER_SIZE=250
	-Isrc/nrf52

[env:wiscore_rak4631]
extends = nrf52

lib_ignore =
    AceButton
    Adafruit TCA8418
    es7210
    ESP32-audioI2S
    lvgl
    SensorLibTDECKPro
    TFT_eSPI
    epdiy
    Timeout
    TinyGSM
    XPowersLib

lib_deps = 
	${libs.lib_deps}
	${nrf52libs.lib_deps}

	; Display Library
	olikraus/U8g2@^2.36.5
	
lib_archive = no
build_flags = 
	${nrf52.build_flags}
	-I variants/${this.__env__}